version: '3.8'

services:
  payment-service:
    build: payment-service
    image: payment-service
    container_name: payment-service-container
    ports:
      - 8088:8088
    depends_on:
      - keycloak
    restart: on-failure
    environment:
      - DEFAULT_BALANCE=3000
      - OAUTH2_SERVER=http://keycloak:8080/realms/intershop

  store-showcase:
    build: store-showcase
    image: store-showcase
    container_name: store-showcase-container
    ports:
      - 8087:8087
    depends_on:
      - store-showcase-db
      - store-showcase-cache
      - keycloak
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_R2DBC_URL=r2dbc:postgresql://store-showcase-db:5432/store-showcase
      - SPRING_DATASOURCE_URL=jdbc:postgresql://store-showcase-db:5432/store-showcase
      - SPRING_DATASOURCE_USER=store-showcase
      - SPRING_DATASOURCE_PASSWORD=store-showcase
      - PAYMENT_CLIENT_HOST=payment-service
      - PAYMENT_CLIENT_PORT=8088
      - spring.data.redis.host=store-showcase-cache
      - spring.data.redis.port=6379
      - OAUTH2_SERVER=http://keycloak:8080/realms/intershop

  store-showcase-db:
    image: postgres:15
    container_name: store-showcase-db-container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - 6541:5432
    environment:
      - POSTGRES_DB=store-showcase
      - POSTGRES_USER=store-showcase
      - POSTGRES_PASSWORD=store-showcase

  store-showcase-cache:
    image: redis:7.4.2-bookworm
    ports:
      - '6379:6379'

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KC_DB: dev-mem
      KC_LOG_LEVEL: INFO
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_IMPORT: "true"
      KC_IMPORT_REALM: /opt/keycloak/realm-intershop.json
    volumes:
      - ./keycloak/realm-intershop.json:/opt/keycloak/data/import/realm-intershop.json:ro
    command:
      - start-dev
      - --import-realm
    ports:
      - '8080:8080'