server:
  port: 8087

spring:
  application:
    name: intershop

  r2dbc:
    url: ${SPRING_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/intershop}
    username: ${SPRING_DATASOURCE_USER:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
    pool:
      enabled: true # Включение пула соединений
      initial-size: 10 # Начальное количество соединений в пуле
      max-size: 50 # Максимальное количество соединений
      max-idle-time: 30s # Время бездействия соединения перед закрытием
      max-life-time: 10m # Максимальное время жизни соединения
      validation-query: SELECT 1 # SQL-запрос для проверки работоспособности соединения

  thymeleaf:
    check-template-location: true
    cache: false

intershop:
  path-for-upload-image: uploads