spring:
  application:
    name: intershop

  datasource:
    url: jdbc:postgresql://localhost:5432/intershop
    driver-class-name: org.postgresql.Driver
    username: sa
    password: sa

server:
  port: 8087