server:
  port: 8087

spring:
  application:
    name: intershop

  datasource:
    url: jdbc:postgresql://localhost:5432/intershop
    driver-class-name: org.postgresql.Driver
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

intershop:
  path-for-upload-image: uploads