server:
  port: 8088

spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_SERVER:http://localhost:8080/realms/intershop}

service:
  default-balance: ${DEFAULT_BALANCE:3000}