server:
  port: 8088

spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/intershop #todo

service:
  default-balance: ${DEFAULT_BALANCE:3000}