import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

plugins {
    id 'java'
    id 'jacoco'
    id 'checkstyle'
    id 'org.springframework.boot' version '3.5.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.gorylenko.gradle-git-properties' version '2.4.2'
    id 'org.openapi.generator' version '7.12.0'
}

springBoot {
    buildInfo()
}

bootJar {
    enabled = true
    launchScript()
}

jar {
    enabled false
}

group = 'ru.yandex.practicum.store.showcase'
version = '1.0.0-SNAPSHOT'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    testCompileOnly {
        extendsFrom testAnnotationProcessor
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation "org.springframework.boot:spring-boot-starter-data-r2dbc"
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    runtimeOnly 'org.postgresql:r2dbc-postgresql'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    runtimeOnly 'org.postgresql:postgresql' // JDBC драйвер для Flyway

    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'
    implementation 'io.swagger.core.v3:swagger-annotations:2.2.34'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity'

    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'com.redis:testcontainers-redis:2.2.2'
    testImplementation 'org.testcontainers:r2dbc'
    testImplementation 'io.projectreactor:reactor-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.register('buildClient', GenerateTask) {
    generatorName.set("java")
    inputSpec.set("$projectDir/../payment-service/src/main/resources/api-spec.yaml")
    outputDir.set(project.layout.buildDirectory.dir('generated-sources/openapi-client').get().asFile.absolutePath)
    skipValidateSpec.set(false)
    packageName.set('ru.yandex.practicum.store.showcase.client')
    modelPackage.set('ru.yandex.practicum.store.showcase.client.model')
    apiPackage.set('ru.yandex.practicum.store.showcase.client.api')
    invokerPackage.set('ru.yandex.practicum.store.showcase.client')
    configOptions.set([
            library        : 'webclient',
            reactive       : 'true',
            useJakartaEe   : 'true',
            java8          : 'true',
            useTags        : 'true',
            sourceFolder   : 'src/main/java',
            openApiNullable: 'false'
    ])
}

sourceSets {
    main {
        java {
            srcDirs += file("$buildDir/generated-sources/openapi-client/src/main/java")
        }
    }
    test {
        java {
            srcDirs += file("$buildDir/generated-sources/openapi-client/src/test/java")
        }
    }
}

compileJava.dependsOn buildClient
compileTestJava.dependsOn buildClient

clean.doLast {
    delete "$projectDir/build/generated/openapi-client"
}

tasks.named('test') {
    failFast = true
    useJUnitPlatform()
    finalizedBy jacocoTestReport
    testLogging {
        events = ['FAILED', 'PASSED', 'SKIPPED']
    }
}

checkstyle {
    configDirectory.set(file("$rootProject.projectDir/checkstyle"))
}

tasks.withType(Checkstyle).configureEach {
    def generatedDir = layout.buildDirectory.dir('generated-sources/openapi-client').get().asFile

    source = source.filter { file ->
        !file.absolutePath.startsWith(generatedDir.absolutePath)
    }
}

jacoco {
    toolVersion = '0.8.12'
}

def jacocoExclusions = [
        'ru/yandex/**/controller/**',
        'ru/yandex/**/service/**',
        'ru/yandex/**/client/**',
        'ru.yandex.practicum.store.showcase.repository.OrderItemRepository',
        'ru.yandex.practicum.store.showcase.dto.OrderDto',
        'ru.yandex.practicum.store.showcase.exception.NotFoundException',
        'ru.yandex.practicum.store.showcase.exception.PaymentException',
        'ru.yandex.practicum.store.showcase.mapper.ItemMapperImpl'
]

jacocoTestCoverageVerification {
    violationRules {
        rule {
            element = 'CLASS'
            excludes = jacocoExclusions.stream().map { it.replace('/', '.') }.collect()
            limit {
                counter = 'INSTRUCTION'
                minimum = 0.3
            }
            limit {
                counter = 'METHOD'
                minimum = 0.3
            }
            limit {
                counter = 'BRANCH'
                minimum = 0.3
            }
        }
    }
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = false
        csv.required = false
    }
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: jacocoExclusions)
        }))
    }
}

check.dependsOn jacocoTestCoverageVerification